name: Bazel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bazel-build:
    name: Bazel build
    runs-on: ubuntu-22.04
    steps:
    - name: Set up bazel
      uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
        external-cache: true

    - name: Cache git folder
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
      with:
        path: substrait-mlir/.git
        key: git-folder

    - name: Checkout project
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        path: substrait-mlir
        submodules: recursive
        persist-credentials: false

    - name: Lint bazel files
      run: |
        cd substrait-mlir
        bazel run @substrait_mlir//:buildifier
        git submodule foreach --recursive git reset --hard  # undo changes in submodules
        git diff --exit-code || (echo 'Please reformat the bazel files, add them to this PR, and run CI again.'; false)

    - name: Compile
      run: |
        cd substrait-mlir
        bazel build @substrait_mlir//...

    - name: Smoke test
      run: |
        cd substrait-mlir
        bazel run @substrait_mlir//:substrait-lsp-server -- --version
        bazel run @substrait_mlir//:substrait-opt -- --version
        bazel run @substrait_mlir//:substrait-translate -- --version
