name: CMake formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run cmake-format
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false
    - name: Format CMake files
      uses: puneetmatharu/cmake-format-lint-action@4ed77e1b4e9ae7b072e4e34c54461316771566c9 # v1.0.8
      with:
        args: --in-place
    - name: Check for diff
      run: |
        git diff --exit-code || (echo 'Please reformat the CMake files, add them to this PR, and run CI again.'; false)
