name: License headers

on: pull_request

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run SPDX license checker
      uses: enarx/spdx@83697cf00cd75e190c0480b91ae209a338b8ccc9  # November 14, 2024
      with:
        licenses: Apache-2.0 WITH LLVM-exception
