name: Markdown formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run markdownlint-cli2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: '**/*.md'
          config: .markdownlint.jsonc
